services:
  fenrir:
    build: .
    container_name: fenrir-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    labels:
      # Traefik labels (optional, if you want to expose bot metrics/health endpoint)
      - "traefik.enable=false"
    volumes:
      - ./logs:/app/logs:rw
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  proxy:
    external: true  # Your existing Traefik proxy network